# Generated by Django 5.0 on 2024-02-07 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0002_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
