# Generated by Django 5.0 on 2024-02-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0003_delete_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('comments', models.TextField(max_length=1000)),
            ],
        ),
    ]
