# Generated by Django 5.0 on 2024-02-10 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0004_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedbackform',
            fields=[
                ('Firstname', models.TextField(max_length=200)),
                ('Lastname', models.TextField(max_length=200)),
                ('Email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('Comments', models.TextField(max_length=200)),
            ],
            options={
                'db_table': 'Feedbackform',
            },
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
