# Generated by Django 5.0 on 2024-02-10 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0005_feedbackform_delete_feedback'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedbackform',
            new_name='Feedbackformde',
        ),
        migrations.AlterModelTable(
            name='feedbackformde',
            table='Feedbackformde',
        ),
    ]
